import { findPart } from './parts.js'
import { getPhysicsV2Settings, setPhysicsV2Settings } from './physics-v2.js'
const PROJECT_KEY='bricklab.project.v2',UI_KEY='bricklab.physics.v2.mass-overlay'
function readProject(){try{return JSON.parse(localStorage.getItem(PROJECT_KEY)||'null')}catch{return null}}
function massData(){const p=readProject();if(!p?.parts?.length)return{mass:0,com:[0,0,0],front:.5,right:.5};let total=0,sx=0,sy=0,sz=0;for(const item of p.parts){const m=findPart(item.partId)?.physics?.massKg??.002,x=item.position?.[0]??0,y=item.position?.[1]??0,z=item.position?.[2]??0;total+=m;sx+=x*m;sy+=y*m;sz+=z*m}const com=[sx/total,sy/total,sz/total],zs=p.parts.map(x=>x.position?.[2]??0),xs=p.parts.map(x=>x.position?.[0]??0),minZ=Math.min(...zs),maxZ=Math.max(...zs),minX=Math.min(...xs),maxX=Math.max(...xs);return{mass:total,com,front:(com[2]-minZ)/Math.max(1,maxZ-minZ),right:(com[0]-minX)/Math.max(1,maxX-minX)}}
function restartPhysics(){const activeTest=document.body.dataset.bricklabTest,build=document.querySelector('.mode[data-mode="build"]'),sim=document.querySelector('.mode[data-mode="simulate"]');if(activeTest){document.querySelector('.mode[data-mode="test"]')?.click();return}if(sim?.classList.contains('active')){build?.click();requestAnimationFrame(()=>sim.click())}}
function install(){const actions=document.querySelector('.top-actions'),viewport=document.querySelector('.viewport-wrap');if(!actions||!viewport)return requestAnimationFrame(install);if(document.getElementById('physicsV2Button'))return;const button=document.createElement('button');button.id='physicsV2Button';button.className='ghost physics-v2-button';button.title='Physics v2 settings';button.innerHTML='<i data-lucide="atom"></i><span>Physics</span>';actions.insertBefore(button,actions.firstChild);const menu=document.createElement('div');menu.id='physicsV2Menu';menu.className='physics-v2-menu hidden';document.body.append(menu)
const renderMenu=()=>{const s=getPhysicsV2Settings();menu.innerHTML=`<div class="pv2-head"><b>PHYSICS V2</b><small>1 stud = 8 mm</small></div><label>QUALITY<select data-pv2-quality><option value="fast">FAST · 60 Hz</option><option value="balanced">BALANCED · 120 Hz</option><option value="accurate">ACCURATE · 180 Hz</option></select></label><label>SELF COLLISION<select data-pv2-self><option value="off">OFF</option><option value="mechanical">MECHANICAL</option><option value="full">FULL</option></select></label><label class="pv2-check"><input type="checkbox" data-pv2-debug> Physics debug <kbd>F8</kbd></label><label class="pv2-check"><input type="checkbox" data-pv2-mass> Mass / COM overlay</label><small class="pv2-note">Changes restart the current simulation/test.</small>`;menu.querySelector('[data-pv2-quality]').value=s.quality;menu.querySelector('[data-pv2-self]').value=s.selfCollision;menu.querySelector('[data-pv2-debug]').checked=s.debug;menu.querySelector('[data-pv2-mass]').checked=localStorage.getItem(UI_KEY)!=='off';menu.querySelector('[data-pv2-quality]').onchange=e=>{setPhysicsV2Settings({quality:e.target.value});restartPhysics()};menu.querySelector('[data-pv2-self]').onchange=e=>{setPhysicsV2Settings({selfCollision:e.target.value});restartPhysics()};menu.querySelector('[data-pv2-debug]').onchange=e=>{setPhysicsV2Settings({debug:e.target.checked});restartPhysics()};menu.querySelector('[data-pv2-mass]').onchange=e=>{localStorage.setItem(UI_KEY,e.target.checked?'on':'off');updateMass()}}
const mass=document.createElement('div');mass.id='massComOverlay';mass.className='mass-com-overlay';viewport.append(mass);function updateMass(){const show=localStorage.getItem(UI_KEY)!=='off'&&document.querySelector('.mode[data-mode="build"]')?.classList.contains('active');mass.classList.toggle('hidden',!show);if(!show)return;const d=massData();mass.innerHTML=`<div><small>PHYSICAL BUILD</small><b>${Math.round(d.mass*1000)} g</b></div><span>COM <b>${d.com.map(v=>v.toFixed(1)).join(' · ')} stud</b></span><span>F / R <b>${Math.round(d.front*100)} / ${Math.round((1-d.front)*100)}</b></span><span>L / R <b>${Math.round((1-d.right)*100)} / ${Math.round(d.right*100)}</b></span>`}
button.onclick=e=>{e.stopPropagation();renderMenu();const r=button.getBoundingClientRect();menu.style.right=`${Math.max(8,innerWidth-r.right)}px`;menu.style.top=`${r.bottom+8}px`;menu.classList.toggle('hidden')};document.addEventListener('pointerdown',e=>{if(!menu.contains(e.target)&&e.target!==button)menu.classList.add('hidden')});const stats=document.getElementById('projectStats');if(stats)new MutationObserver(updateMass).observe(stats,{childList:true,characterData:true,subtree:true});document.querySelectorAll('.mode').forEach(b=>b.addEventListener('click',()=>requestAnimationFrame(updateMass)));window.addEventListener('keydown',e=>{if(e.code!=='F8')return;e.preventDefault();const s=getPhysicsV2Settings();setPhysicsV2Settings({debug:!s.debug});restartPhysics()});updateMass();window.lucide?.createIcons?.({attrs:{'stroke-width':1.8,'aria-hidden':'true'}})}
install()
