const DEMO_BACKUP_KEY='bricklab.demo.backup.v1',PROJECT_KEY='bricklab.project.v2',SCENARIO_KEY='bricklab.test.scenario.v1'
const SCENARIOS={'hill-climb':{id:'hill-climb',short:'HILL',title:'Hill Climb 22°',statusTitle:'HILL CLIMB',bestKey:'bricklab.test.hill-climb.best.v2',bestKind:'time'},'torque-pull':{id:'torque-pull',short:'PULL',title:'Pull / Torque Bench',statusTitle:'PULL / TORQUE',bestKey:'bricklab.test.torque-pull.best.v2',bestKind:'force'},'obstacle-course':{id:'obstacle-course',short:'OBST',title:'Obstacle Course',statusTitle:'OBSTACLE COURSE',bestKey:'bricklab.test.obstacle-course.best.v2',bestKind:'time'},'dyno-bench':{id:'dyno-bench',short:'DYNO',title:'Dyno Bench',statusTitle:'DYNO BENCH',bestKey:'bricklab.test.dyno-bench.best.v2',bestKind:'power'}}
const readScenario=()=>SCENARIOS[localStorage.getItem(SCENARIO_KEY)]?localStorage.getItem(SCENARIO_KEY):'hill-climb',typing=t=>t instanceof HTMLElement&&(/INPUT|TEXTAREA|SELECT/.test(t.tagName)||t.isContentEditable)
window.addEventListener('keydown',e=>{if(e.code==='KeyS'&&!e.shiftKey&&!e.ctrlKey&&!e.metaKey&&!e.altKey&&!typing(e.target)){e.preventDefault();e.stopImmediatePropagation()}},true)
function install(){const build=document.querySelector('.mode[data-mode="build"]'),sim=document.querySelector('.mode[data-mode="simulate"]'),test=document.querySelector('.mode[data-mode="test"]'),status=document.getElementById('statusText'),actions=document.querySelector('.top-actions'),shortcuts=document.getElementById('shortcutsBtn');if(!build||!sim||!test||!status||!actions)return requestAnimationFrame(install);let selected=readScenario(),finished=false,frame=0;const config=()=>SCENARIOS[selected],readProject=()=>{try{return JSON.parse(localStorage.getItem(PROJECT_KEY)||'null')}catch{return null}},best=c=>{const v=Number(localStorage.getItem(c.bestKey));return Number.isFinite(v)&&v>0?v:null},save=(c,v)=>{if(!Number.isFinite(v)||v<=0)return best(c);const old=best(c),better=old==null||(c.bestKind==='time'?v<old:v>old);if(better)localStorage.setItem(c.bestKey,String(v));return best(c)??v},format=(c,v)=>v==null?'—':c.bestKind==='time'?`${v.toFixed(2)}s`:c.bestKind==='force'?`${v.toFixed(2)} N`:`${v.toFixed(2)} W`
if(!document.getElementById('demoProjectBtn')){const current=readProject(),backup=localStorage.getItem(DEMO_BACKUP_KEY),restore=current?.name==='Starter Hill Climber'&&backup,b=document.createElement('button');b.id='demoProjectBtn';b.className='ghost';b.title=restore?'Restore build from before demo':'Load Starter Hill Climber demo';b.innerHTML=restore?'<i data-lucide="history"></i><span>Restore</span>':'<i data-lucide="car-front"></i><span>Demo</span>';b.onclick=async()=>{if(restore){localStorage.setItem(PROJECT_KEY,backup);localStorage.removeItem(DEMO_BACKUP_KEY);location.reload();return}const p=readProject();if(p?.parts?.length)localStorage.setItem(DEMO_BACKUP_KEY,JSON.stringify(p));try{const r=await fetch('./examples/hill-climber.bricklab',{cache:'no-store'});if(!r.ok)throw Error(`Demo HTTP ${r.status}`);localStorage.setItem(PROJECT_KEY,JSON.stringify(await r.json()));localStorage.setItem(SCENARIO_KEY,'hill-climb');location.reload()}catch(err){console.error(err)}};actions.insertBefore(b,shortcuts||null)}
const sync=()=>document.querySelectorAll('[data-test-scenario]').forEach(b=>b.classList.toggle('active',b.dataset.testScenario===selected));if(!document.getElementById('testScenarioSelector')){const sel=document.createElement('div');sel.id='testScenarioSelector';sel.className='test-scenario-selector';sel.setAttribute('aria-label','TEST scenario');sel.innerHTML=Object.values(SCENARIOS).map(x=>`<button type="button" data-test-scenario="${x.id}" title="${x.title}">${x.short}</button>`).join('');test.insertAdjacentElement('afterend',sel);sel.querySelectorAll('button').forEach(b=>b.onclick=e=>{e.stopPropagation();const next=b.dataset.testScenario;if(!SCENARIOS[next]||next===selected)return;selected=next;localStorage.setItem(SCENARIO_KEY,next);sync();if(document.body.dataset.bricklabTest)test.click()})}sync();window.lucide?.createIcons?.({attrs:{'stroke-width':1.8,'aria-hidden':'true'}})
const mark=()=>{document.querySelectorAll('.mode').forEach(b=>b.classList.remove('active'));test.classList.add('active');document.body.dataset.bricklabTest=selected;sync()},clear=()=>{delete document.body.dataset.bricklabTest;cancelAnimationFrame(frame)}
function ensureUi(){const p=document.querySelector('.telemetry-test');if(!p)return null;let meta=p.querySelector('.test-run-meta');if(!meta){meta=document.createElement('div');meta.className='test-run-meta';p.append(meta)}const c=config();if(meta.dataset.scenario!==c.id){meta.dataset.scenario=c.id;const label=c.bestKind==='time'?'TIME':c.bestKind==='force'?'LOAD':'PEAK POWER';meta.innerHTML=`<span>${label} <b data-test-primary>—</b></span><span>BEST <b data-test-best>${format(c,best(c))}</b></span><button type="button" data-test-retry><i data-lucide="rotate-ccw"></i><span>Retry</span></button>`;meta.querySelector('[data-test-retry]').onclick=()=>test.click();window.lucide?.createIcons?.({attrs:{'stroke-width':1.8,'aria-hidden':'true'}})}return p}
const currentResult=(p,c)=>c.bestKind==='time'?Number(p?.dataset.testElapsed||0):c.bestKind==='force'?Number(p?.dataset.testForce||0):Number(p?.dataset.testPower||0)
function update(){if(document.body.dataset.bricklabTest!==selected)return;const p=ensureUi(),c=config(),phase=p?.dataset.testPhase||'SETTLE',primary=p?.querySelector('[data-test-primary]'),statusValue=p?.dataset.testStatus||'RUNNING',value=currentResult(p,c);if(primary){if(phase==='SETTLE')primary.textContent='SETTLE';else if(phase==='COUNTDOWN')primary.textContent=document.querySelector('[data-v2-phase]')?.textContent||'3';else primary.textContent=format(c,value)}if(!finished&&['PASSED','STALLED'].includes(statusValue)){finished=true;const b=save(c,value),be=p?.querySelector('[data-test-best]');if(be)be.textContent=format(c,b);p?.classList.toggle('run-complete',statusValue==='PASSED');p?.classList.toggle('run-failed',statusValue==='STALLED')}if(!finished)frame=requestAnimationFrame(update)}
const originalBuild=build.onclick,originalSim=sim.onclick;build.onclick=e=>{clear();originalBuild?.call(build,e)};sim.onclick=e=>{if(document.body.dataset.bricklabTest)originalBuild?.call(build,e);clear();originalSim?.call(sim,e)};test.onclick=()=>{if(!build.classList.contains('active'))originalBuild?.call(build,new Event('click'));window.__bricklabNextScenario=selected;originalSim?.call(sim,new Event('click'));mark();finished=false;cancelAnimationFrame(frame);frame=requestAnimationFrame(update)}
new MutationObserver(()=>{if(!document.body.dataset.bricklabTest)return;if(status.textContent.startsWith('BUILD'))return clear();if(status.textContent.startsWith('SIMULATE'))status.textContent=status.textContent.replace(/^SIMULATE/,`TEST · ${config().statusTitle}`);mark()}).observe(status,{childList:true,characterData:true,subtree:true})}
install()
