import { test } from 'node:test'
import assert from 'node:assert/strict'
import { access, readFile } from 'node:fs/promises'

const root = new URL('../', import.meta.url)
const TAG = 'parts-5-20260909-visual-v2'

function parts5Imports(source) {
  return [...source.matchAll(/import\(['"](\.\/parts5\/[^?'"\)]+)(?:\?v=([^'"\)]+))?['"]\)/g)]
    .map(match => ({ specifier: match[1], tag: match[2] ?? null }))
}

test('PARTS-5 production modules exist and use one package tag', async () => {
  const runtime = await readFile(new URL('runtime-extensions.js', root), 'utf8')
  const bootstrap = await readFile(new URL('bootstrap.js', root), 'utf8')
  const imports = [...parts5Imports(runtime), ...parts5Imports(bootstrap)]
  assert.ok(imports.length >= 6)
  for (const item of imports) {
    assert.equal(item.tag, TAG, `${item.specifier} uses PARTS-5 cache tag`)
    await access(new URL(item.specifier.replace(/^\.\//, ''), root))
  }
})

test('PARTS-5 refinement layers are final visual owners before physics', async () => {
  const runtime = await readFile(new URL('runtime-extensions.js', root), 'utf8')
  const legacyVisual = runtime.indexOf("import('./part-visual-v3.js')")
  const legacyWheelMaterial = runtime.indexOf("import('./parts3/parts-3-wheel-materials.js?v=parts-3-20260908-mechanical-v1')")
  const parts5v1 = runtime.indexOf(`import('./parts5/visual-overhaul-v1.js?v=${TAG}')`)
  const parts5v2 = runtime.indexOf(`import('./parts5/visual-refinement-v2.js?v=${TAG}')`)
  const driveline = runtime.indexOf(`import('./parts5/driveline-refinement-v2.js?v=${TAG}')`)
  const structural = runtime.indexOf(`import('./parts5/structural-refinement-v2.js?v=${TAG}')`)
  const details = runtime.indexOf(`import('./parts5/detail-refinement-v3.js?v=${TAG}')`)
  const physics = runtime.indexOf("import('./physics-v2.js')")
  assert.ok(legacyVisual >= 0 && legacyWheelMaterial > legacyVisual)
  assert.ok(parts5v1 > legacyWheelMaterial)
  assert.ok(parts5v2 > parts5v1)
  assert.ok(driveline > parts5v2)
  assert.ok(structural > driveline)
  assert.ok(details > structural)
  assert.ok(physics > details)
})

test('editor snap and drivetrain detection consume the same gear mesh math', async () => {
  const snapping = await readFile(new URL('snapping-v3.js', root), 'utf8')
  const drivetrain = await readFile(new URL('drivetrain.js', root), 'utf8')
  const math = await readFile(new URL('parts5/gear-mesh-math-v1.js', root), 'utf8')
  assert.match(snapping, /solveSpurSnap/)
  assert.match(snapping, /solveBevelSnap/)
  assert.match(drivetrain, /evaluateSpurMesh/)
  assert.match(drivetrain, /evaluateBevelMesh/)
  assert.match(math, /targetDistance = a\.pitchRadius \+ b\.pitchRadius/)
  assert.match(math, /apexA = a\.center\.clone\(\)\.addScaledVector/)
  assert.match(math, /solveSpurPhaseAlignment/)
  assert.match(snapping, /phaseCorrection/)
  assert.match(snapping, /gearWorldReference/)
})

test('gear mesh preview renders pitch circles without becoming physics meshes', async () => {
  const ui = await readFile(new URL('parts5/gear-mesh-ui-v1.js', root), 'utf8')
  assert.match(ui, /parts-5-gear-mesh-ui-v2/)
  assert.match(ui, /new THREE\.LineLoop/)
  assert.match(ui, /pitchRadius/)
  assert.match(ui, /parts5GearMeshGuide/)
  assert.match(ui, /TOOTH PHASE/)
  assert.doesNotMatch(ui, /new THREE\.Mesh\([^\n]*pitch/i)
})

test('gear mesh placement explicitly blocks a fake connector/joint', async () => {
  const snapping = await readFile(new URL('snapping-v3.js', root), 'utf8')
  const connections = await readFile(new URL('connections-v3.js', root), 'utf8')
  assert.match(snapping, /kind: 'gear-mesh'/)
  assert.match(snapping, /placementOnly: true/)
  assert.match(snapping, /suppressNextConnectionForEndpoint/)
  assert.match(connections, /placementSuppressions/)
  assert.match(connections, /consumePlacementSuppression/)
})

test('visual overhaul cannot grow authoritative wheel/gear/complex colliders from decorative bounds', async () => {
  const visuals = await readFile(new URL('parts5/visual-overhaul-v1.js', root), 'utf8')
  const refinement = await readFile(new URL('parts5/visual-refinement-v2.js', root), 'utf8')
  const driveline = await readFile(new URL('parts5/driveline-refinement-v2.js', root), 'utf8')
  const structural = await readFile(new URL('parts5/structural-refinement-v2.js', root), 'utf8')
  const details = await readFile(new URL('parts5/detail-refinement-v3.js', root), 'utf8')
  const collider = await readFile(new URL('collider-clearance-v3.js', root), 'utf8')
  const profiles = await readFile(new URL('collider-profiles-v3.js', root), 'utf8')
  assert.match(visuals, /physicsIgnore = true/)
  assert.match(refinement, /physicsIgnore = true/)
  assert.match(driveline, /physicsIgnore = true/)
  assert.match(structural, /physicsIgnore = true/)
  assert.match(details, /colliderProfile/)
  assert.match(details, /ringBoxSpecs/)
  assert.match(profiles, /explicitColliderProfile/)
  assert.match(collider, /cylinder-y/)
  assert.match(collider, /cylinder-z/)
  assert.match(collider, /if \(wheel\)/)
  assert.match(collider, /wheelColliderDimensions\(wheel, relative\.scale\)/)
  assert.match(collider, /if \(gear\)/)
  assert.match(collider, /gear\.pitchRadius/)
  assert.doesNotMatch(collider, /if \(wheel\)[\s\S]{0,600}buildColliderProfile/)
})

test('refinement layers contain the intended high-quality geometry systems', async () => {
  const source = await readFile(new URL('parts5/visual-refinement-v2.js', root), 'utf8')
  const driveline = await readFile(new URL('parts5/driveline-refinement-v2.js', root), 'utf8')
  const structural = await readFile(new URL('parts5/structural-refinement-v2.js', root), 'utf8')
  const details = await readFile(new URL('parts5/detail-refinement-v3.js', root), 'utf8')
  assert.match(source, /function involuteGearOutline/)
  assert.match(source, /function smoothTyreProfile/)
  assert.match(source, /function taperedSpokeGeometry/)
  assert.match(source, /new THREE\.InstancedMesh\(geometry, material, instances\)/)
  assert.match(source, /new THREE\.TubeGeometry/)
  assert.match(source, /createSteeringKnuckleRefined/)
  assert.match(source, /createSteeringRackRefined/)
  assert.match(source, /createShockRodRefined/)
  assert.match(source, /createBushRefined/)
  assert.match(source, /createAxleCouplerRefined/)
  assert.match(driveline, /createUniversalJointRefined/)
  assert.match(driveline, /createCvJointRefined/)
  assert.match(driveline, /helicalTube/)
  assert.match(driveline, /createWormDriveRefined/)
  assert.match(structural, /createLiftarm/)
  assert.match(structural, /createHollowTechnicBrick/)
  assert.match(structural, /trueBores: true/)
  assert.match(details, /createBentBeamRefined/)
  assert.match(details, /createPinRefined/)
  assert.match(details, /createBearingBlockRefined/)
  assert.match(details, /createSuspensionArmRefined/)
  assert.match(details, /createMotorRefined/)
  assert.match(details, /createGearboxRefined/)
  assert.match(details, /createDifferentialRefined/)
})

test('visual QA gallery loads all refinement layers and exposes critical models', async () => {
  await access(new URL('tests/parts5-visual-qa.html', root))
  await access(new URL('tests/parts5-visual-qa.js', root))
  const qa = await readFile(new URL('tests/parts5-visual-qa.js', root), 'utf8')
  assert.match(qa, /visual-refinement-v2/)
  assert.match(qa, /driveline-refinement-v2/)
  assert.match(qa, /structural-refinement-v2/)
  assert.match(qa, /detail-refinement-v3/)
  assert.match(qa, /wheel-tractor/)
  assert.match(qa, /gear-40/)
  assert.match(qa, /bevel-gear-20/)
  assert.match(qa, /wheel-hub/)
  assert.match(qa, /steering-rack-7/)
  assert.match(qa, /shock-rod-5/)
  assert.match(qa, /universal-joint-30/)
  assert.match(qa, /cv-joint-30/)
  assert.match(qa, /worm-drive-8/)
  assert.match(qa, /beam-l-3x3/)
  assert.match(qa, /connector-perpendicular/)
  assert.match(qa, /bearing-block/)
  assert.match(qa, /suspension-arm-5/)
  assert.match(qa, /gearbox-fnr/)
  assert.match(qa, /open-differential/)
})

test('build metadata has advanced to PARTS-5 visual v2 before merge', async () => {
  const badge = await readFile(new URL('physics-error-ui.js', root), 'utf8')
  const versioner = await readFile(new URL('scripts/version-runtime.mjs', root), 'utf8')
  const html = await readFile(new URL('index.html', root), 'utf8')
  assert.match(badge, /const BUILD_ID = 'PARTS-5'/)
  assert.match(badge, new RegExp(`const BUILD_TAG = '${TAG}'`))
  assert.match(versioner, new RegExp(`process\\.argv\\[2\\] \\?\\? '${TAG}'`))
  assert.match(html, new RegExp(`bootstrap\\.js\\?v=${TAG}`))
  assert.doesNotMatch(html, /parts-4-20260908-driveline-v1/)
})
